name: Manual Publish package to GitHub Packages

on:
  workflow_dispatch:
    branches:
      - main
#  release:
#    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.19.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jamilservices'
        cache: 'npm'
        persist-credentials: false
    - name: Install dependencies
      run: npm install
    - name: Publish to GITHUB
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      if: github.repository == 'jamilservicos/jamilservices-custom-class-type-and-definition'